version: "3.8"

services:
    app:
        build:
            context: .
        command: python manage.py runserver 0.0.0.0:8000
        image: djmdb_img
        container_name: djmdb_con
        ports:
            - 8000:8000
        volumes:
            - .:/mdb
        depends_on:
            - pdb

    pdb:
        image: postgres
        container_name: pdb_con
        volumes:
            - ./db/pdb-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres