version: "3.8"

services:
    app:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        image: djmdb_img:1.0
        container_name: djmdb_con
        ports:
            - 8000:8000
        volumes:
            - .:/djmdb
        depends_on:
            - mysqldb
            - pdb
    
    mysqldb:
        image: mysql:5.7
        container_name: mysqldb_con
        volumes:
            - ./db/mysqldb-data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: 'rostockerdevdb'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'true'

    pdb:
        image: postgres
        container_name: pdb_con
        volumes:
            - ./db/pdb-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres